CREATE DATABASE IF NOT EXISTS inventory;

USE inventory;

-- CREATE USER 'replicator'@'%' IDENTIFIED BY 'replpass';
-- GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'replicator'@'%';
-- FLUSH PRIVILEGES;

-- CREATE USER 'debezium'@'%' IDENTIFIED BY 'dbz';
-- GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'debezium'@'%';
-- FLUSH PRIVILEGES;


CREATE TABLE customers (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE KEY
) AUTO_INCREMENT=1001;


